### ISSUE TITLE
运行程序时报错

### ISSUE THREAD

**Issue by dbgeeker** [henson/Answer#10]
我用的是安卓真机，下载了 release 中的文件，配置了 config.yml 后，运行 cmd 时报错，请问作者这是为什么？images 文件夹里也没有图片。
![微信截图_20200324165331](https://user-images.githubusercontent.com/52853938/77406944-5bec1a80-6df0-11ea-9a30-5f5cdf35feae.png)

**Comment by henson** [comment]
数组越界了，可能是sogou查询结果没检索到
