### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by linyoujia22** [henson/Answer#4]
![ux 9 5x_xboy 55 _6a jxh](https://user-images.githubusercontent.com/35480026/35278133-01fb94dc-0084-11e8-8617-e2c697c22be8.png)
请问这个应该怎么解决呢

**Comment by henson** [comment]
好像是结巴分词的包出了问题，你试着更新下包

```go
go get -u -v github.com/yanyiwu/gojieba
```

**Comment by linyoujia22** [comment]
exec: "gcc": executable file not found in %PATH%

更新的时候出现这个咋整呢？

**Comment by henson** [comment]
需要安装MinGW，百度一下，根据操作系统安装对应版本的MinGW
